image: elixir:latest

services:
  - postgres:latest
  
variables:
  POSTGRES_DB: coliving_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  MIX_ENV: "test"
  GITLAB_CI: "true"

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix ecto.create
  - mix ecto.migrate

mix:
  script:
    - mix test
