{{ if $.Values.ingress.enabled }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
{{- with $.Values.ingress.annotations }}
{{ . | toYaml | indent 4 }}
{{- end }}
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
  name: {{ $.Values.name }}-app
spec:
  rules:
  - host: {{ $.Values.host }}
    http:
      paths:
      - backend:
          serviceName: {{ $.Values.name }}-app
          servicePort: 80
        path: /
  tls:
  - hosts:
    - {{ $.Values.host }}
    secretName: {{ $.Values.name }}-app-tls

{{ end }}

