use Mix.Config

secret_key_base = Application.get_env(:coliving, :secret_key_base)
port = Application.get_env(:coliving, :port)
host = Application.get_env(:coliving, :host)
database_url = Application.get_env(:coliving, :database_url)
pool_size = Application.get_env(:coliving, :pool_size)

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :coliving, ColivingWeb.Endpoint,
  load_from_system_env: true,
  url: [host: host, port: 80],
  server: true,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :coliving, Coliving.Repo,
  # ssl: true,
  url: database_url,
  pool_size: pool_size

config :coliving, ColivingWeb.Endpoint,
  http: [
    port: port,
    transport_options: [socket_opts: [:inet6]]
  ],
  secret_key_base: secret_key_base
